/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSkillsRouteImport } from './routes/_chat.skills'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatMcpRouteImport } from './routes/_chat.mcp'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSkillsRoute = ChatSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatMcpRoute = ChatMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/mcp': typeof ChatMcpRoute
  '/settings': typeof ChatSettingsRoute
  '/skills': typeof ChatSkillsRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/mcp': typeof ChatMcpRoute
  '/settings': typeof ChatSettingsRoute
  '/skills': typeof ChatSkillsRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/mcp': typeof ChatMcpRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/skills': typeof ChatSkillsRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$threadId' | '/mcp' | '/settings' | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to: '/$threadId' | '/mcp' | '/settings' | '/skills' | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/mcp'
    | '/_chat/settings'
    | '/_chat/skills'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/skills': {
      id: '/_chat/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof ChatSkillsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/mcp': {
      id: '/_chat/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof ChatMcpRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatMcpRoute: typeof ChatMcpRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatSkillsRoute: typeof ChatSkillsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatMcpRoute: ChatMcpRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatSkillsRoute: ChatSkillsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
